### ISSUE TITLE
advised of way of protecting resources/routes?

### ISSUE THREAD

**Issue by rquintino** [Azure-Samples/active-directory-python-webapp-graphapi#14]
Hi team, thanks for this sample! 
question: is there any work on setting this up for proper protection of routes in flask ? 
ex like authlib decorators?
```
@app.route('/user')
@require_oauth()
def user_profile():
    ...
```
Also seeing this, how does this compares?
https://github.com/antarctica/flask-azure-oauth

other solutions?

thanks!

**Comment by rquintino** [comment]
also related, which is the advised/up to date version?
https://github.com/microsoftgraph/python-sample-auth/blob/master/sample_flask.py

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Python library. Check it out: https://github.com/Azure-Samples/ms-identity-python-webapp. This is the most up to date and recommended sample to follow.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
