### ISSUE TITLE
/graphcall doesn't do any auth validation

### ISSUE THREAD

**Issue by prburgu** [Azure-Samples/active-directory-python-webapp-graphapi#5]
There is a serious security issue with this sample. The `/graphcall` doesn't do any auth validation. The session object at https://github.com/Azure-Samples/active-directory-python-webapp-graphapi/blob/master/app.py#L13 is global and it will be used for any `/graphcall` call. So once someone authenticates, any subsequent calls to `/graphcall` use the same auth token.

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
* access https://host.name/ and complete the login flow
* access https://host.name/graphcall for another browser/curl and you see the data of the first user.

**Comment by navyasric** [comment]
Thanks for reporting this issue. We are looking into it and will follow up with an update.

**Comment by navyasric** [comment]
@prburgu The fix was merged for this issue. Please try it out. Closing for now.
