### ISSUE TITLE
/groups?$filter=startswith(displayName, 'AA') resulting in Bad Request

### ISSUE THREAD

**Issue by mastgupta** [Azure-Samples/active-directory-python-webapp-graphapi#7]
I have this simple search function in Flask to lookup groups names but it always ends up in a result saying badly formed request and a status: 400.

@APP.route('/search')
def search(top=10):
    params = request.args.to_dict()  
    term = params.get('term')
    queryMembers = "groups?$filter=startswith(displayName, 'AA')"
    print("AAA", queryMembers)
    result = MSGRAPH.get(queryMembers, headers=request_headers()).data
    return flask.render_template('query_2.html', result=result)

need help on figuring out what wrong I am doing.

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Python library. Check it out: https://github.com/Azure-Samples/ms-identity-python-webapp

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
